{% set name = "imageai" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9f821b5c9138514169527129771a6105ae213bc0e2df471d55e43a1fd36d841

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - h5py
    - matplotlib-base
    - numpy
    - pillow
    - python >=3.6
    - scipy
    - opencv
    - keras
    - click
    - scikit-learn
    - keras-resnet
    - tensorflow

test:
  imports:
    - imageai
    - imageai.Detection
    - imageai.Detection.Custom
    - imageai.Detection.Custom.utils
    - imageai.Detection.YOLO
    - imageai.Detection.keras_retinanet
    - imageai.Detection.keras_retinanet.backend
    - imageai.Detection.keras_retinanet.bin
    - imageai.Detection.keras_retinanet.callbacks
    - imageai.Detection.keras_retinanet.layers
    - imageai.Detection.keras_retinanet.models
    - imageai.Detection.keras_retinanet.preprocessing
    - imageai.Detection.keras_retinanet.utils
    - imageai.Prediction
    - imageai.Prediction.Custom
    - imageai.Classification
    - imageai.Classification.Custom

about:
  home: https://github.com/OlafenwaMoses/ImageAI
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python library built to empower developers to build applications and systems  with self-contained Computer Vision capabilities
  dev_url: https://github.com/OlafenwaMoses/ImageAI

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
